- pipeline: demodeployment
  name: DemoDeployment
  refs:
  - refs/heads/main
  fail_on_prepare_env_warning: true
  events:
  - type: WEBHOOK
  actions:
  - action: npm run build
    type: BUILD
    execute_commands:
    - "# yarn install"
    - npm install
    - npm run build
    shell: BASH
    docker_image_name: library/node
    docker_image_tag: 22
